version: '1.0'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "80:80"

  backend:
    build:
      context: ./server 
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/NovaJet
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: